### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/docker-compose-wordpress#8]
- [ ] Can we access log files as it is? From host location?
- [ ] Does `docker logs` exposes some magic?

**Comment by vishaldodiya** [comment]
> Can we access log files as it is? From host location?

One can map log files from docker container to host files. for example,

```
  nginx:
    image: nginx:latest
    depends_on:
      - php
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/nginx/log/error.log:/var/log/nginx/error.log"
      - "./config/nginx/log/access.log:/var/log/nginx/access.log"
```

---

> Does docker logs exposes some magic?

In docker logs command one can get log from specific container using container name or container id, like

```
$ docker logs -f <container_id>/<container_name>
```
Reference https://docs.docker.com/engine/reference/commandline/logs/

---

Also one can use docker-compose log to get logs from all services.
Reference https://docs.docker.com/compose/reference/logs/
